-- 017: 회원 프로필 필드 (항목 15) — 첫 로그인 온보딩에서 수집·DB 저장.
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS nickname VARCHAR(40);
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS phone VARCHAR(20);
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS real_name VARCHAR(40);
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS onboarded BOOLEAN NOT NULL DEFAULT FALSE;
