-- 042: 라이브러리 에셋 개편 — 단색(에디터 색변경 지원) 누끼 PNG 아이콘 세트.
-- 기존 시드(/assets/library/ 경로형)만 교체하고 관리자 업로드(data: URL)는 보존.
DELETE FROM design_assets WHERE image LIKE '/assets/library/%';

INSERT INTO design_assets (kind, name, image, sort) VALUES
  ('free', '비행기', '/assets/library/free/airplane-engines-fill.png', 0),
  ('free', '하트풍선', '/assets/library/free/balloon-heart-fill.png', 1),
  ('free', '자전거', '/assets/library/free/bicycle.png', 2),
  ('free', '붓', '/assets/library/free/brush-fill.png', 3),
  ('free', '카메라', '/assets/library/free/camera-fill.png', 4),
  ('free', '구름', '/assets/library/free/cloud-fill.png', 5),
  ('free', '게임패드', '/assets/library/free/controller.png', 6),
  ('free', '커피', '/assets/library/free/cup-hot-fill.png', 7),
  ('free', '다이아', '/assets/library/free/diamond-fill.png', 8),
  ('free', '하트눈', '/assets/library/free/emoji-heart-eyes-fill.png', 9),
  ('free', '선글라스', '/assets/library/free/emoji-sunglasses-fill.png', 10),
  ('free', '불꽃', '/assets/library/free/fire.png', 11),
  ('free', '꽃1', '/assets/library/free/flower1.png', 12),
  ('free', '꽃2', '/assets/library/free/flower2.png', 13),
  ('free', '꽃3', '/assets/library/free/flower3.png', 14),
  ('free', '보석', '/assets/library/free/gem.png', 15),
  ('free', '하트', '/assets/library/free/heart-fill.png', 16),
  ('free', '무한대', '/assets/library/free/infinity.png', 17),
  ('free', '번개', '/assets/library/free/lightning-charge-fill.png', 18),
  ('free', '달과별', '/assets/library/free/moon-stars-fill.png', 19),
  ('free', '음표', '/assets/library/free/music-note-beamed.png', 20),
  ('free', '팔레트', '/assets/library/free/palette-fill.png', 21),
  ('free', '피스', '/assets/library/free/peace-fill.png', 22),
  ('free', '로켓', '/assets/library/free/rocket-takeoff-fill.png', 23),
  ('free', '눈송이', '/assets/library/free/snow2.png', 24),
  ('free', '별', '/assets/library/free/star-fill.png', 25),
  ('free', '반짝임', '/assets/library/free/stars.png', 26),
  ('free', '하트2', '/assets/library/free/suit-heart-fill.png', 27),
  ('free', '태양', '/assets/library/free/sun-fill.png', 28),
  ('free', '나무', '/assets/library/free/tree-fill.png', 29),
  ('free', '트로피', '/assets/library/free/trophy-fill.png', 30),
  ('free', '우산', '/assets/library/free/umbrella-fill.png', 31);

INSERT INTO design_assets (kind, name, image, sort) VALUES
  ('patch', '어워드', '/assets/library/patch/award-fill.png', 0),
  ('patch', '종', '/assets/library/patch/bell-fill.png', 1),
  ('patch', '과녁', '/assets/library/patch/bullseye.png', 2),
  ('patch', '나침반', '/assets/library/patch/compass-fill.png', 3),
  ('patch', '커피', '/assets/library/patch/cup-hot-fill.png', 4),
  ('patch', '스마일', '/assets/library/patch/emoji-smile-fill.png', 5),
  ('patch', '불꽃', '/assets/library/patch/fire.png', 6),
  ('patch', '깃발', '/assets/library/patch/flag-fill.png', 7),
  ('patch', '꽃', '/assets/library/patch/flower1.png', 8),
  ('patch', '보석', '/assets/library/patch/gem.png', 9),
  ('patch', '하트', '/assets/library/patch/heart-fill.png', 10),
  ('patch', '번개', '/assets/library/patch/lightning-charge-fill.png', 11),
  ('patch', '달과별', '/assets/library/patch/moon-stars-fill.png', 12),
  ('patch', '음표', '/assets/library/patch/music-note-beamed.png', 13),
  ('patch', '체크', '/assets/library/patch/patch-check-fill.png', 14),
  ('patch', '로켓', '/assets/library/patch/rocket-fill.png', 15),
  ('patch', '방패', '/assets/library/patch/shield-fill.png', 16),
  ('patch', '별', '/assets/library/patch/star-fill.png', 17),
  ('patch', '클로버', '/assets/library/patch/suit-club-fill.png', 18),
  ('patch', '다이아', '/assets/library/patch/suit-diamond-fill.png', 19),
  ('patch', '스페이드', '/assets/library/patch/suit-spade-fill.png', 20),
  ('patch', '태양', '/assets/library/patch/sun-fill.png', 21),
  ('patch', '나무', '/assets/library/patch/tree-fill.png', 22),
  ('patch', '트로피', '/assets/library/patch/trophy-fill.png', 23);
